# [build]
#   publish = "dist"
#   command = "npm run build"
#   functions = "netlify/functions"
#   commandOrigin= "config"
#   publishOrigin= "config"

[build]
  command= "npm run build"
  commandOrigin= "config"
  publish= "/opt/build/repo/dist"
  publishOrigin= "config"
  functionsDirectory= "/opt/build/repo/netlify/functions"
